use_field_init_shorthand = true
use_try_shorthand = true

# Unstable
unstable_features = true

imports_granularity = "crate"
group_imports = "StdExternalCrate"

wrap_comments = true 
format_code_in_doc_comments = true 

